### ISSUE TITLE
Template generation

### ISSUE THREAD

**Issue by janstenpickle** [shantytown/shanty#1]

**Comment by nathankleyn** [comment]
So talking more about this:

* We should have a template plugin.
* We should have a data source plugin.
* Templates should have a dependency on any data sources they need to work.
* Projects should have a dependency on any templates they need to work.

This simple change resolves all the issues around deciding what templates to build for what.

**Comment by nathankleyn** [comment]
The work for this has been shipped out to shantytown/properties-file-plugin#5 and shantytown/template-plugin#1.
